### PR TITLE
1st commit

### PR DESCRIPTION
**Pull request by BobbyGatlin**

### CODE REVIEW

**Comment by BobbyGatlin** [comment]
I don't quite understand why it failed. When I run the runner everything seems to be correct

**Comment by jashhhhhhh** [comment]
you don't need the "example=[1000,etc]" matrix in the q1 file because its in the runner file

**Comment by BobbyGatlin** [comment]
Yay got it. Thank you.

**Comment by halfaro1** [comment]
@BobbyGatlin great work!

**Pull request closed without merging**
