### PR TITLE
Midterm

### PR DESCRIPTION
**Pull request by MarcialSegura**

### CODE REVIEW

**Comment by halfaro1** [comment]
What about Q1 @MarcialSegura ?

**Comment by MarcialSegura** [comment]
Hey Professor! I just sync Q1.py so sorry! I didn't realize it wasnt, hope it's right.


________________________________

**Comment by halfaro1** [comment]
@MarcialSegura looks good, but check your indentations, this is the error from the automated checks:
```
test_midterm.py:5: in <module>
    import q2
E     File "/home/travis/build/valencia-cop1000-201620/midterm/q2.py", line 47
E       global sticks
E                   ^
E   IndentationError: unindent does not match any outer indentation level
```

**Comment by MarcialSegura** [comment]
Hey Professor, I'm not sure if your still checking the Mid-Term py. but I tried to resubmit the file.


________________________________

**Comment by halfaro1** [comment]
@MarcialSegura fantastic work - thanks for the correction!

**Pull request closed without merging**
